<a href="https://colab.research.google.com/github/AymaneDame/Multiple-Classification-with-CNN/blob/main/Classification_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTATION

In [ ]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import scipy
from PIL import Image
from scipy import ndimage
import tensorflow as tf
from tensorflow.python.framework import ops

import matplotlib.pyplot as plt
import numpy as np
from keras import losses 
from keras import optimizers 
from keras import metrics 
from tensorflow import keras

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.optimizers import SGD

Le dataset se trouve dans la biblio Keras

In [ ]:
fashion_mnist = mist = tf.keras.datasets.fashion_mnist

assignations des training datas(60000) et des test data(1000) à 4 variables.

In [ ]:
(train_images, train_labels) , (test_images, test_labels) = fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step
<module 'keras.api._v2.keras.datasets.fashion_mnist' from '/usr/local/lib/python3.7/dist-packages/keras/api/_v2/keras/datasets/fashion_mnist/__init__.py'>


In [ ]:
print(train_images)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


normalisation

In [ ]:
# print('Valeur maximum de nos images : ',np.min(train_images1))
# print('Valeur minimum de nos images : ', np.max(train_labels1))

# train_images = train_images1.astype('float32')/255
# train_labels = train_labels1.astype('float32')/255

# print('Valeur maximum de nos images normalisées : ',np.min(X_train))
# print('Valeur minimum de nos images normalisées : ',np.max(X_train))

construction du modèle

In [ ]:
model = Sequential()

Convolution

In [ ]:
model.add(Conv2D(32,      #le nombre de filtres de sortie dans la convolution
                 kernel_size=(3, 3), #le filtre/patch/kernel
                 activation='relu',
                 input_shape=(28,28,1)))  #la taille de l'image d'entrée
model.add(Conv2D(32, 
                 kernel_size=(3, 3),
                 activation='relu'))

Max Pooling

In [ ]:
model.add(MaxPooling2D(pool_size=(2, 2))) #réduire la dim de l'image (average/max pooling.)

Flatten

In [ ]:
model.add(Flatten())

FC

In [ ]:
# model = keras.Sequential([
#                           keras.layers.Flatten(input_shape = (28, 28)),
#                           keras.layers.Dense(512, activation="relu"),
#                           keras.layers.Dense(128, activation="relu"),
#                           keras.layers.Dense(10, activation="softmax")

# ])
# model.add(Dense(512, activation='relu'))
model.add(Dense(128, activation='relu'))#128 neuronnes
model.add(Dense(10, activation='softmax'))

In [ ]:
# model.compile(loss="categorical_crossentropy")
model.compile(loss = 'sparse_categorical_crossentropy',optimizer = 'adam', metrics = ['accuracy'])
# model.compile(loss="categorical_crossentropy", optimizer=SGD(lr=0.01), metrics=["accuracy"])

In [ ]:
model.fit(train_images, train_labels,epochs = 10 )#epochs nbr de rétropropagation

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5633 - accuracy: 0.8513
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2725 - accuracy: 0.8993
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2259 - accuracy: 0.9151
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1912 - accuracy: 0.9275
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1623 - accuracy: 0.9409
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1358 - accuracy: 0.9499
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1140 - accuracy: 0.9581
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1038 - accuracy: 0.9629
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0850 - accuracy: 0.9695
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.080

Tester le modèle sur les données test

In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels, verbose=2)#evaluer le modèle entrainé avec le jeu de données test.

313/313 - 1s - loss: 0.5167 - accuracy: 0.8973 - 714ms/epoch - 2ms/step


VISUALISER LES PARAM DE 

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_11 (Conv2D)          (None, 26, 26, 32)        320       
                                                                 
 conv2d_12 (Conv2D)          (None, 24, 24, 32)        9248      
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 12, 12, 32)       0         
 2D)                                                             
                                                                 
 flatten_4 (Flatten)         (None, 4608)              0         
                                                                 
 dense_11 (Dense)            (None, 128)               589952    
                                                                 
 dense_12 (Dense)            (None, 10)                1290      
                                                      

Enregistrer les weights du modèle (enregistrer le modèle entrainé)

In [ ]:
model.save_weights("model.h5")